spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/community
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        #use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  
  mvc:
    hiddenmethod:
      filter:
        enabled: true    

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type.descriptor.sql: trace
  #org.hibernate.type: trace


  
file:
  dir: E:/Development/eclipse-workspace/storage/file/
  tmpdir: E:/Development/eclipse-workspace/storage/tmp/