spring:
  config:
    activate:
      on-profile: prod
  banner:
    location: prod-banner.txt

  #datasource:
   # url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&characterEncoding=UTF-8
    #username: root
    #password: tp1346790
    #driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cache:
    redis:
      time-to-live: 86400000

  redis:
    port: 6379
    host: ${REDIS_HOST}

logging:
  level:
    p6spy: error

    org:
      apache:
        coyote:
          http11: info

  file:
    path: E:/Development/eclipse-workspace/storage/log

file:
  dir: E:/Development/eclipse-workspace/storage/file/
  tmpdir: E:/Development/eclipse-workspace/storage/tmp/

#server:
 # port: 5000

cloud:
  aws:
    stack:
      auto: false